[package]
name = "axplat-riscv64-common"
version = "0.1.0"
description = "RISC-V common codes with `axplat` compatibility"
documentation = "https://docs.rs/axplat-riscv64-common"
keywords = ["arceos", "os", "hal", "riscv64"]
categories = ["embedded", "no-std", "hardware-support", "os"]
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
irq = ["axplat/irq"]
rtc = ["riscv_goldfish"]

[dependencies]
kspin = "0.1"
lazyinit = "0.2"
log = "0.4"
ns16550a = "0.5.0"
plic = { git = "https://github.com/Starry-Mix-THU/plic.git", rev = "ee40f86" }
riscv = "0.14"
riscv_goldfish = { version = "0.1", optional = true }
sbi-rt = { version = "0.0.3", features = ["legacy"] }

axconfig-macros = "0.2"
axcpu = { workspace = true }
axplat = { workspace = true }

[package.metadata.docs.rs]
targets = ["riscv64gc-unknown-none-elf"]
