# Architecture identifier.
arch = "riscv64"                                # str
# Platform identifier.
platform = "visionfive2"                        # str
# Platform package.
package = "axplat-riscv64-visionfive2"          # str

#
# Platform configs
#
[plat]
# Number of CPUs.
cpu-num = 4                                     # uint
# Base address of the whole physical memory.
phys-memory-base = 0x4000_0000                  # uint
# Size of the whole physical memory. (1G)
phys-memory-size = 0x4000_0000                  # uint
# Base physical address of the kernel image.
kernel-base-paddr = 0x4020_0000                 # uint
# Base virtual address of the kernel image.
kernel-base-vaddr = "0xffff_ffc0_4020_0000"     # uint
# Linear mapping offset, for quick conversions between physical and virtual
# addresses.
phys-virt-offset = "0xffff_ffc0_0000_0000"      # uint
# Offset of bus address and phys address. some boards, the bus address is
# different from the physical address.
phys-bus-offset = 0                             # uint
# Kernel address space base.
kernel-aspace-base = "0xffff_ffc0_0000_0000"    # uint
# Kernel address space size.
kernel-aspace-size = "0x0000_003f_ffff_f000"    # uint
# Stack size on bootstrapping. (256K)
boot-stack-size = 0x40000                       # uint

#
# Device specifications
#
[devices]
# MMIO ranges with format (`base_paddr`, `size`).
mmio-ranges = [[0x0, 0x4000_0000]]              # [(uint, uint)]
# VirtIO MMIO ranges with format (`base_paddr`, `size`).
virtio-mmio-ranges = []                         # [(uint, uint)]
# Base physical address of the PCIe ECAM space.
pci-ecam-base = 0x2b00_0000                     # uint
# End PCI bus number.
pci-bus-end = 0xff                              # uint
# PCI device memory ranges.
pci-ranges = []                                 # [(uint, uint)]

# Timer interrupt frequency in Hz.
timer-frequency = 4_000_000                     # uint
# Timer interrupt num.
timer-irq = "0x8000_0000_0000_0005"             # uint

# VisionFive 2 RTC
rtc-paddr = 0x1704_0000                         # uint

plic-paddr = 0x0c00_0000                        # uint

uart-paddr = 0x1000_0000                        # uint
uart-interrupt = 0x20                           # uint
